services:

    postgres:
      image: postgres:16
      container_name: catalog-postgres
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "5433:5432"
      volumes:
        - catalog_postgres_data:/var/lib/postgresql/data
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
          ]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 10s


    catalog-service:
      image: ${IMAGE_NAME}:${IMAGE_TAG}
      build: .
      container_name: catalog-service
      restart: unless-stopped

      ports:
        - "${PORT:-8081}:8081"

      environment:
        SPRING_PROFILES_ACTIVE: ${APP_PROFILE:-}
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
        SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
        SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        SECRET: ${JWT_SECRET}
        CORS_ORIGINS: ${CORS_ORIGINS}
        SERVER_PORT: 8082

      depends_on:
        postgres:
          condition: service_healthy

volumes:
  catalog_postgres_data: