CREATE TABLE tb_stock_reservation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT      NOT NULL,
    product_id BIGINT      NOT NULL,
    quantity   INTEGER     NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    status     VARCHAR(20) NOT NULL,
    CONSTRAINT fk_stock_reservation_product
        FOREIGN KEY (product_id)
            REFERENCES tb_product (id)
);

ALTER TABLE tb_product
    ADD COLUMN reserved_stock INTEGER NOT NULL DEFAULT 0;